export enum EventName  {
    LOGIN = 'login-activity',
    ACCOUNT_CREATION = 'register-activity',
    LOGOUT = 'logout-activity',
    ROLE_CREATION = 'role-creation-activity',
    PROFILE_CREATION = 'profile-creation-activity',
    PROFILE_VERIFICATION = 'profile-verification-activity',

    ACTIVITY = 'user-activity'
}

export enum ActivityType {
    ROOM_CREATED = 'Room created.',
    ROOM_BOOKING_CREATED = 'Booking created.',
    ROOM_COMPLETE_BOOKING_STATUS = 'Booking completed.',
    ROOM_APPROVE_BOOKING_STATUS = 'Booking approved.',
    ROOM_CANCEL_BOOKING_STATUS = 'Booking cancelled.',
    FOOD_CREATED = 'Food created.',
    FOOD_DELETED = 'Food deleted.',
    FOOD_ORDER_CREATED = 'Order created.',
    FOOD_COMPLETE_ORDER_STATUS = 'Order delivered.',
    FOOD_CANCEL_ORDER_STATUS = 'Order cancelled.',

    ROLE_CREATION = 'Role created.',
    PROFILE_CREATION = 'Profile created.',
    PROFILE_VERIFICATION = 'Account approved.',
    LOGIN = 'Login successfully.',
    LOGIN_SAVED = 'Saved login.',
    LOGIN_FAILURE = 'Login failed.',
    LOGOUT = 'Logout successfully',
    ACCOUNT_CREATION = 'Account created',
    WITHDRAWAL_CREATION = 'WITHDRAWAL_CREATION',
    DEPOSIT_CREATION = 'DEPOSIT_CREATION',
    ORDER_PLACEMENT = 'ORDER_PLACEMENT',
    ORDER_CANCELLATION = 'ORDER_CANCELLATION',
    ACCOUNT_WALLET_CHANGES = 'ACCOUNT_WALLET_CHANGES',
    ACCOUNT_SETTING_CHANGES = 'ACCOUNT_SETTING_CHANGES',
    ACCOUNT_PROFILE_CHANGES = 'ACCOUNT_PROFILE_CHANGES',
    SYSTEM_ERROR = 'SYSTEM_ERROR',
    API_REQUEST = 'API_REQUEST',
    SECURITY_EVENT = 'SECURITY_EVENT',
    ADMIN_ACTION = 'ADMIN_ACTION',
    EMAIL_NOTIFICATION = 'EMAIL_NOTIFICATION',
    SMS_NOTIFICATTION = 'SMS_NOTIFICATTION',
}